#!/bin/bash

FIRST_ROBOT_ID=0
ROBOTS_IN_CONTAINER=25
ROS_BRIDGE_URL="ws://0.0.0.0:9090"
IS_MAIN_CONTAINER=true
JADE_MAIN_CONTAINER_HOST="192.165.0.153"
JADE_MAIN_CONTAINER_PORT=10098

cd target && java -jar jade_container.jar $FIRST_ROBOT_ID $ROBOTS_IN_CONTAINER $ROS_BRIDGE_URL $IS_MAIN_CONTAINER $JADE_MAIN_CONTAINER_HOST $JADE_MAIN_CONTAINER_PORT